apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "titan.fullname" . }}-config
  labels:
    {{- include "titan.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
